### ISSUE TITLE
Campaign Controller

### ISSUE THREAD

**Issue by stack72** [GiveCampUK/GiveCRM#3]
Hey guys

there is a large dependency on the DataAccess layer throughout the campaign controller. This is caused by a new instance of the DataAccess layer being called in a lot of methods in this way:

Campaigns db = new Campaigns();
            Campaign savedCampaign = db.Insert(campaign);
            return savedCampaign.Id;

We really need to get this moved out of the Controller

I think this would be a big milestone for Separation of Concerns

Paul

**Comment by nbarnwell** [comment]
Yes, our controllers need to go on a diet. We have IoC and a Services namespace for this, we just need to move the appropriate amount of that stuff out into those services. They're auto-wired so if you put "IMyFunkyNewService" as a ctor arg of a controller, it will automatically make sure that the MyFunkyNewService concrete instance is passed-in.

**Comment by kendallmiller** [comment]
This is one of those points where there is a bit of complexity we need to manage.as we go about this.  There are many databases (conceptually) - one for each charity.  So we need to have it be super-easy and obvious when writing the modules how to get the current charity database and very hard to get the wrong one.  This is so we can have multi-tennant application instances and be very confident we're never cross-connecting the data.

The central database needs to know all of the instances so it can redirect traffic to the right places (and provision/remove databases)

**Comment by Lethrir** [comment]
Hi Paul,

I have to confess that in the dying minutes I could get a hold of the 'I can change the proj file' pill / batton so I had to add a db ref into the QuickDonate view as I couldn't add a ViewModel file... Please don't shoot me but it might want fixing while you're at it...

Cheers,

Kim.

**Comment by stack72** [comment]
I agree Kendall - we need to be able to handle this correctly - I am working on separating the layers for now for cleanliness - that way we can work efficiently on the multi tennant aspect of the project :)

Kim dont worry - it needs to be shipped :)

Neil I have been working under that assumption all morning ;)
