### ISSUE TITLE
CRM: The "Download template" link doesn't work

### ISSUE THREAD

**Issue by nbarnwell** [GiveCampUK/GiveCRM#36]
# Reproduction steps
1. Go the Excel Importer by visiting /ExcelImport
2. Click the Download Excel Template link
# Expected
1. The Excel Template file downloads to disk successfully.
# Actual
1. An error is thrown and the template does not download.
# Notes

This was broken when the Excel Importer was moved to the main application.  The Excel Template is still in the GiveCRM.Admin repository, and is being embedded into the GiveCRM.Admin.Web assembly.  It should be moved to the GiveCRM.Web assembly.

**Comment by alastairs** [comment]
Fixed with pull request #71.
