### ISSUE TITLE
Build System

### ISSUE THREAD

**Issue by stack72** [GiveCampUK/GiveCRM#4]
Ok for now I am going to hook up my teamcity server to GiveCRM repo and build it from there - i will also make a test site on my server and push deploys to there

i will work along the assumption of check in causes deployment for now

that way you can all monitor the progress - if anyone has any objections say ay!

Paul

**Comment by alastairs** [comment]
> i will work along the assumption of check in causes deployment for now

Sounds great! Will you be putting "gates" in place so that failed builds and test failures prevent that change from being deployed?

**Comment by stack72** [comment]
for sure - a successful build and successful unit test run (I will be adding a lot more of these) will cause a build and deploy :)

**Comment by alastairs** [comment]
Cool! Some of us got round to writing tests, others didn't. The way of the weekend, I guess.

**Comment by AnthonySteele** [comment]
CI is good. Thanks Paul!

**Comment by stack72** [comment]
Ok the build will be on my build server

teamcity.paulstack.co.uk:8000

there is a giveCRM user
user: givecrm
pw: givecampuk

you can monitor the build on there

More to come on this

**Comment by robinminto** [comment]
Any chance we can have a CI build for GiveCRM.Admin too please?

We'll have the same database project dependency that we have for GiveCRM by the way (Mark built both DB layers identically).

**Comment by alastairs** [comment]
@stack72 Thanks for setting this up!  One question: how are the builds triggered?  I just checked TeamCity and there were two changes pending that had been sat there since yesterday evening.  I ran a build manually...  

Not sure why Chris' change didn't fix the build either.

**Comment by stack72** [comment]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v10.0\TeamData\Microsoft.Data.Schema.TSqlTasks.targets" was not found

there is another reference to those TeamData GAC references - the build is now triggered by VCS checkin

**Comment by stack72** [comment]
@robinminto of course - i will set that one up in a bit (during lunch!)

**Comment by chrisjdiver** [comment]
Ah, sorry about that, looks like that file references two others in the program files directory.

If no-one objects i'll add the files and push to the repo.

**Comment by stack72** [comment]
@chris - go for it mate

**Comment by chrisjdiver** [comment]
I've added the files, but the build failed with a new error, looks like a library that comes with VS2010.

I found this on stackoverflow, might have to drop that project from the build? 

http://stackoverflow.com/questions/3988879/getting-msbuild-and-cruisecontrol-net-to-build-and-deploy-vs2010-database-proje

**Comment by alastairs** [comment]
Ewwww, I feel dirty just reading the line,

> The only way to do this and be in line with the licensing and support is to install a local copy of VS Pro or higher on your build box if not using TFS.

**Comment by stack72** [comment]
We are not installing VS on a build server - I just cannot allow it!

**Comment by kendallmiller** [comment]
I love CI and I applaud the notion that we don't want to install VS on the build server, although it's a line I've never managed to hold (there are just too many good extensions that use it..) In this case though since portability of the project is important I think we have to keep a "no installing anything on the build server" rule intact.  That may mean we have to take a different approach to databse schema management.  For example, I've used an approach on our commercial products that is a PITA but ensures we can always upgrade databases at runtime when applications are fired up.

**Comment by alastairs** [comment]
Based on our email discussions, @markrendle has some plans around the database and Simple.Data that would remove our dependency on the database projects.

**Comment by stack72** [comment]
Ok I have had to not include the DataBase project as part of the build - this means that we now have a successful build using PSake :) 

I will tidy the script and then start auto deploy script to test.givecrm.org.uk
