### ISSUE TITLE
Admin: Provision the site

### ISSUE THREAD

**Issue by nbarnwell** [GiveCampUK/GiveCRM#47]
Create new IIS website [or virtual machine, Azure instance, etc.]

There's some discussion about this not being strictly necessary, if we can tell (via host headers or through the URL) the CRM which database to connect to. This would be preferable, because then requests can be shared across a horizontally-scaled cluster, rather than siloing each charity to their own CRM instance.

**Comment by alastairs** [comment]
Moved to https://github.com/GiveCampUK/GiveCRM.Admin/issues/8
