### ISSUE TITLE
db project

### ISSUE THREAD

**Issue by stack72** [GiveCampUK/GiveCRM#5]
Guys the db project doesnt build unless you have visual studio installed

Please can someone check the following file into a /src/tools folder and reference the file in the dataaccess project from this tools folder rather than program files folder

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v10.0\TeamData\Microsoft.Data.Schema.SqlTasks.targets

Thanks

Paul

**Comment by chrisjdiver** [comment]
I've added and pushed the change. 

Last push to the main repo honest :) 

Chris
