### ISSUE TITLE
Admin: Activation

### ISSUE THREAD

**Issue by nbarnwell** [GiveCampUK/GiveCRM#55]
This comment is from Alastair on the LeanKitKanBan board we were using:

> Activate a charity's site when the activation link is visited.
> Configure subdomain using our default generated "short name"
> Charity ID: pass to Core UI for setting up DB connection, etc.  Take from activation URL?

**Comment by alastairs** [comment]
Moved to https://github.com/GiveCampUK/GiveCRM.Admin/issues/4
