### ISSUE TITLE
CRM: ASP.NET page compile error on donations page

### ISSUE THREAD

**Issue by nbarnwell** [GiveCampUK/GiveCRM#56]
# Steps to replicate
1. Open CRM site
2. Click "Donations" on menu bar
# Expected result

The donations page to appear.
# Action result

An exception is thrown in _Views/Donation/Index.cshtml_ (see below).
# Exception detail

> System.Web.HttpException was unhandled by user code
>  Message=Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'.
>  Source=System.Web
>  ErrorCode=-2147467259
>  WebEventCode=0
>  StackTrace:
>       at System.Web.HttpServerUtility.ExecuteInternal(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage, VirtualPath path, VirtualPath filePath, String physPath, Exception error, String queryStringOverride)
>       at System.Web.HttpServerUtility.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage)
>       at System.Web.HttpServerUtility.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm)
>       at System.Web.HttpServerUtilityWrapper.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm)
>       at System.Web.Mvc.Html.ChildActionExtensions.ActionHelper(HtmlHelper htmlHelper, String actionName, String controllerName, RouteValueDictionary routeValues, TextWriter textWriter)
>       at System.Web.Mvc.Html.ChildActionExtensions.RenderAction(HtmlHelper htmlHelper, String actionName, String controllerName)
>       at ASP._Page_Views_Donation_Index_cshtml.Execute() in c:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Donation\Index.cshtml:line 25
>       at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
>       at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
>       at System.Web.WebPages.StartPage.RunPage()
>       at System.Web.WebPages.StartPage.ExecutePageHierarchy()
>       at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
>       at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
>       at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
>       at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
>       at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
>       at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19()
>       at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
>  InnerException: System.Web.HttpCompileException
>       Message=c:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml(35): error CS1026: ) expected
>       Source=System.Web
>       ErrorCode=-2147467259
>       WebEventCode=0
>       SourceCode=#pragma checksum "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "4722FD71B23E0A111F69AC5F99792055"
> //------------------------------------------------------------------------------
> // <auto-generated>
> //     This code was generated by a tool.
> //     Runtime Version:4.0.30319.239
> //
> //     Changes to this file may cause incorrect behavior and will be lost if
> //     the code is regenerated.
> // </auto-generated>
> //------------------------------------------------------------------------------
> 
> namespace ASP {
>    using System;
>    using System.Collections.Generic;
>    using System.IO;
>    using System.Linq;
>    using System.Net;
>    using System.Web;
>    using System.Web.Helpers;
>    using System.Web.Security;
>    using System.Web.UI;
>    using System.Web.WebPages;
>    using System.Web.Mvc;
>    using System.Web.Mvc.Ajax;
>    using System.Web.Mvc.Html;
>    using System.Web.Routing;
> 
>    #line 2 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
>    using GiveCRM.Web.Models.Members;
> 
>    #line default
>    #line hidden
> 
>    #line 3 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
>    using PagedList.Mvc;
> 
>    #line default
>    #line hidden
> 
>    public class _Page_Views_Member_MembersList_cshtml : System.Web.Mvc.WebViewPage<PagedMemberListViewModel> {
> # line hidden
> 
> ```
>    public _Page_Views_Member_MembersList_cshtml() {
>    }
> 
>    protected ASP.global_asax ApplicationInstance {
>        get {
>            return ((ASP.global_asax)(Context.ApplicationInstance));
>        }
>    }
> 
>    public override void Execute() {
> 
> 
> 
> 
> 
>        #line 4 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
> ```
> 
>    Layout = null;
> 
> ```
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral("\r\n<script src=\"");
> 
> ```
>        #line 8 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
>    Write(Url.Content("~/Scripts/ViewScripts/MemberList.js"));
> 
> 
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral("\" type=\"text/javascript\"></script>\r\n<script type=\"text/javascript\">\r\n\r\n    $(func" +
> "tion () {\r\n        MemberList.Initialise()\r\n    });\r\n\r\n</script>\r\n\r\n");
> 
> ```
>        #line 17 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
> ```
> 
> if (Model != null && Model.Count > 0)
> {
> 
> ```
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral("<table>\r\n\r\n    <tr>\r\n        <th>&nbsp;</th>\r\n        <th>&nbsp;</th>\r\n        <t" +
> "h>&nbsp;</th>\r\n        <th>Reference</th>\r\n        <th>Name</th>\r\n        <th>Ad" +
> "dress</th>\r\n        <th>Email</th>\r\n    </tr>\r\n\r\n");
> 
> ```
>        #line 31 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
> foreach (var member in Model)
> ```
> 
>    {
> 
> ```
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral("        <tr>\r\n            <td>");
> 
> ```
>        #line 34 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
>       Write(Html.ActionLink("Edit", "Edit", new { id = member.Id }));
> 
> 
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral("</td>\r\n            <td>");
> 
> ```
>        #line 35 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
>       Write(Html.ActionLink("Delete", "Delete", new { id = member.Id } new { title = "ref_" + member.Reference }));
> 
> 
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral("</td>\r\n            <td>");
> 
> ```
>        #line 36 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
>       Write(Html.ActionLink("Log Donation", "Donate", new { id = member.Id }));
> 
> 
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral("</td>\r\n            <td>");
> 
> ```
>        #line 37 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
>       Write(member.Reference);
> 
> 
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral("</td>\r\n            <td>");
> 
> ```
>        #line 38 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
>       Write(member.Salutation);
> 
> 
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral(" ");
> 
> ```
>        #line 38 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
>                          Write(member.FirstName);
> 
> 
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral(" ");
> 
> ```
>        #line 38 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
>                                            Write(member.LastName);
> 
> 
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral("</td>\r\n            <td>");
> 
> ```
>        #line 39 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
>       Write(member.AddressLine1);
> 
> 
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral(" ");
> 
> ```
>        #line 39 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
>                            Write(member.AddressLine2);
> 
> 
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral(" ");
> 
> ```
>        #line 39 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
>                                                 Write(member.City);
> 
> 
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral(" ");
> 
> ```
>        #line 39 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
>                                                              Write(member.PostalCode);
> 
> 
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral("</td>\r\n            <td>");
> 
> ```
>        #line 40 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
>       Write(member.EmailAddress);
> 
> 
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral("</td>\r\n        </tr>\r\n");
> 
> ```
>        #line 42 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
> ```
> 
>    }
> 
> ```
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral(@"
>    <tr>
>        <td colspan=""7"" style=""text-align: center"">
>            <style type=""text/css"">
>              .PagedList-pager ul li
>              {
>                  display: inline;
>                  margin: 0 5px;
>              }
> 
> ```
>          .PagedList-currentPage { font-weight: bold; }
>          .PagedList-currentPage a { color: Black; }
>        </style>
>        ");
> 
> 
> 
>        #line 56 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
>   Write(Html.PagedListPager(Model, Model.PagingFunction, PagedListRenderOptions.OnlyShowFivePagesAtATime));
> 
> 
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral("\r\n        </td>\r\n    </tr>\r\n</table>\r\n");
> 
> ```
>        #line 60 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
> ```
> 
> }
> else
> {
> 
> ```
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral("    <p>Your search returned no results.</p>\r\n");
> 
> ```
>        #line 64 "C:\Code\GiveCampUK2011\GiveCRM_nbarnwell\src\GiveCRM.Web\Views\Member\MembersList.cshtml"
> ```
> 
> }
> 
> ```
>        #line default
>        #line hidden
> ```
> 
> WriteLiteral("\r\n\r\n");
> 
> ```
>    }
> ```
> 
>    }
> }
> 
> ```
>   StackTrace:
>        at System.Web.Compilation.AssemblyBuilder.Compile()
>        at System.Web.Compilation.BuildProvidersCompiler.PerformBuild()
>        at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
>        at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
>        at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
>        at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound)
>        at System.Web.Mvc.BuildManagerWrapper.System.Web.Mvc.IBuildManager.FileExists(String virtualPath)
>        at System.Web.Mvc.BuildManagerViewEngine.FileExists(ControllerContext controllerContext, String virtualPath)
>        at System.Web.Mvc.VirtualPathProviderViewEngine.GetPathFromGeneralName(ControllerContext controllerContext, List`1 locations, String name, String controllerName, String areaName, String cacheKey, String[]& searchedLocations)
>        at System.Web.Mvc.VirtualPathProviderViewEngine.GetPath(ControllerContext controllerContext, String[] locations, String[] areaLocations, String locationsPropertyName, String name, String controllerName, String cacheKeyPrefix, Boolean useCache, String[]& searchedLocations)
>        at System.Web.Mvc.VirtualPathProviderViewEngine.FindView(ControllerContext controllerContext, String viewName, String masterName, Boolean useCache)
>        at System.Web.Mvc.ViewEngineCollection.<>c__DisplayClassc.<FindView>b__b(IViewEngine e)
>        at System.Web.Mvc.ViewEngineCollection.Find(Func`2 lookup, Boolean trackSearchedPaths)
>        at System.Web.Mvc.ViewEngineCollection.FindView(ControllerContext controllerContext, String viewName, String masterName)
>        at System.Web.Mvc.ViewResult.FindView(ControllerContext context)
>        at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
>        at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
>        at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19()
>        at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
>        at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1c.<>c__DisplayClass1e.<InvokeActionResultWithFilters>b__1b()
>        at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
>        at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
>        at System.Web.Mvc.Controller.ExecuteCore()
>        at System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext)
>        at System.Web.Mvc.ControllerBase.System.Web.Mvc.IController.Execute(RequestContext requestContext)
>        at System.Web.Mvc.MvcHandler.<>c__DisplayClass6.<>c__DisplayClassb.<BeginProcessRequest>b__5()
>        at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass1.<MakeVoidDelegate>b__0()
>        at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass8`1.<BeginSynchronous>b__7(IAsyncResult _)
>        at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End()
>        at System.Web.Mvc.MvcHandler.<>c__DisplayClasse.<EndProcessRequest>b__d()
>        at System.Web.Mvc.SecurityUtil.<GetCallInAppTrustThunk>b__0(Action f)
>        at System.Web.Mvc.SecurityUtil.ProcessInApplicationTrust(Action action)
>        at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
>        at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result)
>        at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerAsyncWrapper.<>c__DisplayClassa.<EndProcessRequest>b__9()
>        at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerWrapper.<>c__DisplayClass4.<Wrap>b__3()
>        at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerWrapper.Wrap[TResult](Func`1 func)
>        at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerWrapper.Wrap(Action action)
>        at System.Web.Mvc.HttpHandlerUtil.ServerExecuteHttpHandlerAsyncWrapper.EndProcessRequest(IAsyncResult result)
>        at System.Web.HttpServerUtility.ExecuteInternal(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage, VirtualPath path, VirtualPath filePath, String physPath, Exception error, String queryStringOverride)
>   InnerException:
> ```

**Comment by alastairs** [comment]
Working on this as we speak.

**Comment by alastairs** [comment]
Fixed in pull request #59.
