### ISSUE TITLE
Data Generator: generate better campaigns

### ISSUE THREAD

**Issue by adrianbanks** [GiveCampUK/GiveCRM#60]
The current data generator can only generate members and campaigns, with the campaigns being committed and having no members.

The data generator needs updating so that it can create:
- uncommitted campaigns
- committed campaigns
- closed campaigns
  
  (all of which should have search criteria, and hence members)

**Comment by alastairs** [comment]
It _may_ also be necessary to add the Phone Number Types to Members in the Data Generator.  There are currently three failing tests in the GiveCRM.DataAccess project that I haven't been able to fix up myself.

**Comment by adrianbanks** [comment]
I'll take a look at that as well, and fix them if I can.

**Comment by adrianbanks** [comment]
I consider this feature complete, and it has been merged to master. There is a small issue where searching for the members of a campaign run gives an error (see issue #74), but I believe that is an issue in the data access layer which I haven't yet tracked down.
