### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by chrisjdiver** [GiveCampUK/GiveCRM#8]
The GiveCRM.Web project has a two files referenced in .csproj which are not part of the repo. Can whoever knows about them please add / delete them as required.

Views/Shared/_LogOnPartial.cshtml 
Views/Setup/AddFacetOption.cshtml 

Thanks, 
Chris

**Comment by Lethrir** [comment]
AddFacetOption.cshtml is not needed any more.

Not sure about _LogOnPartial.cshtml thou.

**Comment by AnthonySteele** [comment]
You can remove AddFacetOption.cshtml - the later idea was that the 
Add/Edit facet page would also handle the options.

**Comment by chrisjdiver** [comment]
_LogOnPartial is part of the MVC template, so I suspect someone delete that too, and the merge problems we had left it referenced in the csproj file. I'll fix that tonight, thanks chaps.

**Comment by chrisjdiver** [comment]
Fixed in the pull request.
